### ISSUE TITLE
[FE] 메인페이지 추가작업

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#107]
## Description

메인페이지 배너 제대로 동작하지 않음 -> 재구현
카테고리별 인기상품 쿼리 안감 -> 버그 수정
데이터가 일반값으로 들어가있는 것들 -> 코드 수정
api 구조 리팩토링

## Todo

- [x] 배너 수정
- [x] 카테고리별 인기상품 데이터 받아오지 못하는 버그 수정
- [x] 상품리스트 코드 수정
- [x] api 구조 리팩토링

## ETC
- 주의 사항 혹은 기타 내용
