### ISSUE TITLE
[FE] 로그인(header 문제) 통신 로직

### ISSUE THREAD

**Issue by raon9401** [dailyAuction/project_daily_auction#117]
## Description

header에서 필요한 데이터 추출

## Todo

- [x] header에 담길 데이터 확인
- [x] 통신 로직 수정
- [x] 로그인 후 데이터 처리

## ETC
- 주의 사항 혹은 기타 내용
