### ISSUE TITLE
[FE] 페이지 동작확인

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#143]
## Description

서버연결후 정상적으로 통신하고, 데이터 화면상에 나타나는지 확인

## Todo

- [x] 메인페이지 (글자수정 및 적용되어있지않던 부분 수정)
- [x] 내등록페이지, 내참여페이지 (statusId값 변경(진행중0, 낙찰1, 유찰2 -> 진행중1, 낙찰2, 유찰3)
- [x] 상품등록페이지( 유효성검사-이미지등록필수, 내용입력필수, 검사 걸릴시 모달 close, 이미지 업로드 코드수정, 카테고리 적용 안되는 현상 수정, 카테고리 드롭다운에서 전체카테고리 버튼 제거)

## ETC
- 주의 사항 혹은 기타 내용
