### ISSUE TITLE
[FE] 입찰 후 현재 보유 코인 업데이트 요청하기

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#159]
## Description

상세페이지에서 입찰 후 현재 보유한 코인 잔액 업데이트하도록 요청 보내기

## Todo

- [x] 요청 로직 작성하기
- [x] 로직 적용하기 (입찰 이후 바로 조회하도록)
- [x] (추가 수정) 연속 입찰 방지하도록 버튼 숨기기
- [x] 입찰한 뒤에 시작가, 내 입찰가 업데이트를 위해 refetch 로직 작성하기

## ETC
- 주의 사항 혹은 기타 내용
