### ISSUE TITLE
[FE] SSE 연결 후 알림, 코인 등 상태 업데이트 로직 작성하기

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#166]
## Description

현재 메인 헤더에 위치한 SSE 연결 로직을 바탕으로 알림 기능 구현해야함!

## Todo

- [x] SSE 연결 전역으로 관리하기
- [x] 알림 데이터 리액트 쿼리 등 상태로 저장하여 관리하기
- [x] 전체 알림 데이터 요청해서 동기화 하는 로직
  - [x] 새로고침시
  - [x] 처음 컴포넌트 마운트시에
- [x] 알림 페이지에서 알림 컴포넌트 렌더링하기
- [x] 알림 삭제 로직 구현하기
- [x] 헤더 컴포넌트에서 알림 갯수 확인하기
- [x] 헤더 컴포넌트에서 알림 데이터로 코인 잔액 업데이트 시마다 화면 업데이트하도록 수정
- [x] 알림 전역에서 수신할 수 있도록 연결 위치 변경

## ETC
- 주의 사항 혹은 기타 내용
