### ISSUE TITLE
[FE] 기타 수정

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#168]
## Todo

- [x] 아이폰 확장자(heic) 이미지 업로드 가능하게 구현
- [x] 상품등록페이지 모달창에서 유효성 검사 -> 페이지에서 바로 검사
- [x] 낙찰시 판매자 이메일 추가
- [x] 기타 쿼리옵션 변경
