### ISSUE TITLE
[FE] 상품 상세페이지 퍼블리싱 

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#17]
## Description

![image](https://user-images.githubusercontent.com/89173923/216894353-90c84b0c-8df7-4709-ba9b-62f489243afb.png)
![image](https://user-images.githubusercontent.com/89173923/216894374-1bc0e666-d3dd-47fd-938c-f9c8d2b057f1.png)

## Todo

- [x] 이미지 리스트 컴포넌트
- [x] 남은 시간 및 상태 컴포넌트
- [x] 가격, 입찰 횟수, 액션 버튼 컴포넌트
- [x] 경매가 입력 모달창
- [x] 이미지 확대보기 모달창

## ETC
- [x] 데이터 없이 일단 퍼블리싱 
- [x] 목데이터 만들고 적용
- [x] 상태에 따라 조건부 렌더링 적용
