### ISSUE TITLE
[FE] 배포 준비

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#190]
## Description

배포를 위해 준비해야할 내용

## Todo

- [x] css 버그 픽스
  - [x] TAB BAR CSS 수정 (FIXED)
  - [x] 모바일에서 로그인 확인 필요시에 알림이 뜨지 않는 문제 수정
  - [x] Chart.js 순서가 이미지보다 앞으로 나와있는 현상 해결
- [x] S3 설정
- [x] GITHUB ACTION 설정 후 배포
- [x] main 브랜치에 merge 후 도메인 연결

## ETC
- 주의 사항 혹은 기타 내용
