### ISSUE TITLE
[FE] 기능 추가 구현

### ISSUE THREAD

**Issue by raon9401** [dailyAuction/project_daily_auction#191]
## Description

추가 기능 구현

## Todo

- [ ] 로그인 만료 시 알림 모달 추가
- [ ] 로그인 성공 시 경로 이동 수정
- [ ] 로컬스토리지 훅 구현
- [ ] 카테고리 리스트 인피니티 스크롤 추가

## ETC
- 주의 사항 혹은 기타 내용
