### ISSUE TITLE
[FE] 가로 터치스크롤, 버그픽스

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#213]
## Description
* 모바일 환경과 마찬가지로 pc에서도 가로 드래그시(마우스 클릭한 상태에서 좌우로 이동) 상품 이동되는 기능 구현
* 각종 버그 수정

## Todo

기능 추가
- [x] 마감임박상품 터치스크롤
- [x] 카테고리별 인기상품 버튼 터치스크롤
- [x] 상품등록시 이미지 삭제 기능

오류 수정 
- [x] 렌더링시 시간 깜빡거림 해결
- [x] 마감임박상품 포커싱 리패치 제거(너무 많은 요청을 보내므로)
- [x] 마감임박상품 실시간 데이터 업데이트(마운트시 업데이트 되도록 설정)
- [x] 터치스크롤 drag end시에 마우스 커서가 상품 위에 있다면 클릭으로 간주되어 상품페이지로 이동하는 현상 수정 -> 어렵다..
- [x] 상품등록버튼 빠르게 연속클릭시 상품 여러번 등록되는 문제 수정

##  작업시간
평일 20:00 ~ 24:00 / 2~3일 소요 예정
