### ISSUE TITLE
[FE] 검색 페이지 퍼블리싱

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#38]
## Description

검색페이지 퍼블리싱
![image](https://user-images.githubusercontent.com/89173923/217455220-a9702ffe-497f-4ed5-b450-0826cdb10590.png)

## Todo

- [x] 검색 인풋창 퍼블리싱
- [x] 카테고리 버튼 퍼블리싱
- [x] 인기 검색어 리스트

## ETC
- 응답 mock 데이터 만들어서 렌더링
- 쿼리 등 api 연결 고려하여 설계
