### ISSUE TITLE
[FE] 페이지 디자인 - 마이페이지, 비밀번호 수정, 예치금 충전 페이지

### ISSUE THREAD

**Issue by raon9401** [dailyAuction/project_daily_auction#45]
## Description

페이지 디자인

## Todo
- 마이페이지
- [x] 마이페이지
- [x] 회원탈퇴 모달
- 비밀번호 수정
- [x] 비밀번호 수정 페이지
- [x] 비밀번호 확인 모달
- 예치금 충전 페이지
- [x] 예치금 충전 페이지
- [x] 충전 확인 모달

## ETC
- 주의 사항 혹은 기타 내용
