### ISSUE TITLE
[FE] 게시글 상세페이지 로직 구현

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#55]
## Description

* 게시글 상세페이지 api 연결을 위한 로직 구현

## Todo

- [x] 남은 시간 카운트하는 함수 만들기
- [x] 로그인 여부 확인하여 로그인 페이지로 이동시키는 함수 만들기
- [x] 리액트 쿼리를 적용하기 위한 로직 셋팅
- [x] #93

## ETC
- 주의 사항 혹은 기타 내용
