### ISSUE TITLE
[FE] 페이지 기능 추가 - 회원가입 로직 구현

### ISSUE THREAD

**Issue by raon9401** [dailyAuction/project_daily_auction#67]
## Description

이메일,비밀번호 유효성 검사 구현
이메일 인증 모달 구현

## Todo

- [x] 이메일 유효성 검사
- [x] 비밀번호 유효성 검사
- [x] 이메일 인증 모달 구현
