### ISSUE TITLE
[FE] 메인페이지 로직 작성

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#68]
## Description

메인페이지

## Todo

- [x] 카테고리 디자인 수정, 버튼클릭시 색상변경

- [x] 마감임박상품 통신로직
- [x] 전체 인기상품,카테고리별 인기상품 통신로직

- [x] 리액트쿼리 기본세팅
- [x] 마감임박상품 리액트쿼리 적용
- [x] 전체인기상품, 카테고리별 인기상품 리액트쿼리 적용
