### ISSUE TITLE
[FE] 게시글 상세페이지 Chart.js 적용하기 + 요청 로직 마무리

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#93]
## Description

게시글 상세페이지에 Chart.js 로 꺽쇠 그래프 적용할 것.
그리고 입찰 요청 로직 작성하기

## Todo

- [x] 라이브러리 분석
- [x] 필요한 코드 확인
- [x] 필요한 데이터 타입 확인
- [x] 적용
- [x] 경매가 유효성 검사 (숫자만 입력되도록 하는 유틸 함수 `blockInvalidChar`구현
- [x] 리액트쿼리 post로 입찰 요청 로직 작성하기

## ETC
- 주의 사항 혹은 기타 내용
