### ISSUE TITLE
[FE] api 로직 분리, 쿼리 옵션 설정

### ISSUE THREAD

**Issue by halmokme** [dailyAuction/project_daily_auction#95]
## Todo

- [x] 내등록경매, 내참여경매 api 로직 분리
- [x] 마감임박상품, 카테고리별 인기상품 api 로직 분리
- [x] 글로벌 쿼리 옵션 설정
- [x] 마감임박상품 쿼리옵션 변경
