### ISSUE TITLE
[FE] 웹소켓 로직 작성

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#98]
## Description

웹소켓 로직 작성

## Todo

- [x] 웹소켓 라이브러리 선정
- [x] 동작 방식 파악
- [x] 어떤 컴포넌트에서 데이터 받아올 것인지 결정
- [x] 로직 작성 및 연결
- [x] 통신 테스트 후 수정
  - [x] initial 데이터 요청 후 렌더링 확인
  - [x] 입찰 요청
  - [x] 실시간 업데이트 및 렌더링 확인

## ETC
- 주의 사항 혹은 기타 내용
