### ISSUE TITLE
[FE] 알림 컴포넌트 SSE 연결 로직 작성

### ISSUE THREAD

**Issue by hyejj19** [dailyAuction/project_daily_auction#99]
## Description

알림 페이지에서 SSE로 데이터 받아오는 로직 작성하기

## Todo

- [x] SSE 로직 구현 코드 레퍼런스 참조
- [x] 어떤 컴포넌트에서 데이터 받아올 것인지 결정
- [x] 연결 로직 구현
- [x] 통신 테스트

## ETC
- 주의 사항 혹은 기타 내용
